### ISSUE TITLE
bug in calculating area in srv_ngals

### ISSUE THREAD

**Issue by nsevilla** [patricialarsen/descqa#9]
I think the area should be calculated like this:

area = (xbins[1]-xbins[0]) * np.pi/180. * (np.sin(ybins[1] * np.pi/180.)-np.sin(ybins[0] * np.pi/180.)) # area of rectangular section in steradians
area = area * np.power(180./np.pi,2)*60.*60. # steradians to square arc minutes

**Comment by patricialarsen** [comment]
Good catch, will fix.

**Comment by patricialarsen** [comment]
should be fixed in latest commit

**Comment by nsevilla** [comment]
I think the latest commit is still missing a factor np.power(180./np.pi,2) to convert from steradians to square degrees.
